package mtg_rpg;

import java.awt.Dimension;
import java.awt.Toolkit;

public class RES {
	public static final Dimension SCREEN_SIZE = Toolkit.getDefaultToolkit().getScreenSize();
	public static final int DUEL_INSET = 100;
	public static enum GAME_STATES{
		CHOOSE_FIRST,
		PLAYER_MULLIGAN,
		ENEMY_MULLIGAN,
		PLAYER_TURN_0,
		ENEMY_TURN_0,
		PLAYER_UNTAP,
		PLAYER_UPKEEP,
		PLAYER_DRAW,
		PLAYER_PRE_MAIN,
		PLAYER_BEGIN_COMBAT,
		PLAYER_POST_MAIN,
		PLAYER_END,
		PLAYER_CLEANUP,
		ENEMY_UNTAP,
		ENEMY_UPKEEP,
		ENEMY_DRAW,
		ENEMY_PRE_MAIN,
		ENEMY_BEGIN_COMBAT,
		ENEMY_POST_MAIN,
		ENEMY_END,
		ENEMY_CLEANUP,
	}
	/*
	public static final int 
		//Life Counter
		LIFE_GRDIX = 0,
		LIFE_GRIDWIDTH = 5,
		LIFE_GRIDHEIGHT = 2,
		
		E_LIFE_GRIDY = 0,
		P_LIFE_GRIDY = 24,
		
		//Mana labels
		MANA_L_GRIDX = 5,
		MANA_L_GRIDWIDTH = 2,
		MANA_L_GRIDHEIGHT = 1,
		
		E_MANA_W_GRIDY = 0,
		E_MANA_U_GRIDY = 1,
		E_MANA_R_GRIDY = 2,
		E_MANA_G_GRIDY = 3,
		E_MANA_B_GRIDY = 4,
		E_MANA_X_GRIDY = 5,
		
		P_MANA_W_GRIDY = 20,
		P_MANA_U_GRIDY = 21,
		P_MANA_R_GRIDY = 22,
		P_MANA_G_GRIDY = 23,
		P_MANA_B_GRIDY = 24,
		P_MANA_X_GRIDY = 25,
		
		//ManaValues
		MANA_V_GRIDX = 7,
		MANA_V_GRIDWIDTH = 3,
		MANA_V_GRIDHEIGHT = 1,
		
		//Hand, Deck, Grave, Exile
		HAND_DECK_GRAVE_EXILE_L_GRIDX = 0,
		HAND_DECK_GRAVE_EXILE_V_GRIDX = 3,
		HAND_DECK_GRAVE_EXILE_L_GRIDWIDTH = 3,
		HAND_DECK_GRAVE_EXILE_L_GRIDHEIGHT = 1,
		HAND_DECK_GRAVE_EXILE_V_GRIDWIDTH = 2,
		HAND_DECK_GRAVE_EXILE_V_GRIDHEIGHT = 1,
		
		E_HAND_GRIDY = 2,
		E_EXILE_GRIDY = 3,
		E_GRAVE_GRIDY = 4,
		E_DECK_GRIDY = 5,
		
		P_HAND_GRIDY = 20,
		P_EXILE_GRIDY = 21,
		P_GRAVE_GRIDY = 22,
		P_DECK_GRIDY = 23,
		
		//Card Display
		CARD_DISPLAY_GRIDX = 0,
		CARD_DISPLAY_GRIDY = 6,
		CARD_DISPLAY_GRIDWIDTH = 10,
		CARD_DISPLAY_GRIDHEIGHT = 14,
		
		//Battlefields
		BATTLE_GRIDX = 10,
		BATTLE_GRIDWIDHT = 30,
		BATTLE_GRIDHEIGHT = 13,
		
		E_BATTLE_GRIDY = 0,
		P_BATTLE_GRIDY = 13;
		
		*/
	public static final int 
	//Life Counter
	LIFE_GRDIX = 0,
	LIFE_GRIDWIDTH = 2,
	LIFE_GRIDHEIGHT = 2,
	
	E_LIFE_GRIDY = 0,
	P_LIFE_GRIDY = 11,
	
	//Mana labels
	MANA_L_GRIDX = 2,
	MANA_L_GRIDWIDTH = 1,
	MANA_L_GRIDHEIGHT = 1,
	
	E_MANA_W_GRIDY = 0,
	E_MANA_U_GRIDY = 1,
	E_MANA_R_GRIDY = 2,
	E_MANA_G_GRIDY = 3,
	E_MANA_B_GRIDY = 4,
	E_MANA_X_GRIDY = 5,
	
	P_MANA_W_GRIDY = 7,
	P_MANA_U_GRIDY = 8,
	P_MANA_R_GRIDY = 9,
	P_MANA_G_GRIDY = 10,
	P_MANA_B_GRIDY = 11,
	P_MANA_X_GRIDY = 12,
	
	//ManaValues
	MANA_V_GRIDX = 3,
	MANA_V_GRIDWIDTH = 1,
	MANA_V_GRIDHEIGHT = 1,
	
	//Hand, Deck, Grave, Exile
	HAND_DECK_GRAVE_EXILE_L_GRIDX = 0,
	HAND_DECK_GRAVE_EXILE_V_GRIDX = 1,
	HAND_DECK_GRAVE_EXILE_L_GRIDWIDTH = 1,
	HAND_DECK_GRAVE_EXILE_L_GRIDHEIGHT = 1,
	HAND_DECK_GRAVE_EXILE_V_GRIDWIDTH = 1,
	HAND_DECK_GRAVE_EXILE_V_GRIDHEIGHT = 1,
	
	E_HAND_GRIDY = 2,
	E_EXILE_GRIDY = 3,
	E_GRAVE_GRIDY = 4,
	E_DECK_GRIDY = 5,
	
	P_HAND_GRIDY = 7,
	P_EXILE_GRIDY = 8,
	P_GRAVE_GRIDY = 9,
	P_DECK_GRIDY = 10,
	
	//Card Display
	CARD_DISPLAY_GRIDX = 0,
	CARD_DISPLAY_GRIDY = 6,
	CARD_DISPLAY_GRIDWIDTH = 4,
	CARD_DISPLAY_GRIDHEIGHT = 1,
	
	//Battlefield
	BATTLE_GRIDX = 4,
	BATTLE_GRIDWIDHT = 1,
	BATTLE_GRIDHEIGHT = 13,
	BATTLE_GRIDY = 0;
		
}
